/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CanonCamera */

#ifndef _Included_CanonCamera
#define _Included_CanonCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CanonCamera
 * Method:    openSession
 * Signature: ()Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_openSession
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    closeSession
 * Signature: ()Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_closeSession
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setCamRefFromList
 * Signature: (I)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setCamRefFromList
  (JNIEnv *, jobject, jint);

/*
 * Class:     CanonCamera
 * Method:    releaseCamRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_camera_1api_canon_CanonCamera_releaseCamRef
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    productName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_camera_1api_canon_CanonCamera_productName
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    bodyIDEx
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_camera_1api_canon_CanonCamera_bodyIDEx
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setOwnerName
 * Signature: (Ljava/lang/String;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setOwnerName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     CanonCamera
 * Method:    getOwnerName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_camera_1api_canon_CanonCamera_getOwnerName
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setCopyright
 * Signature: (Ljava/lang/String;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setCopyright
  (JNIEnv *, jobject, jstring);

/*
 * Class:     CanonCamera
 * Method:    getCopyright
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_camera_1api_canon_CanonCamera_getCopyright
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    firmwareVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_camera_1api_canon_CanonCamera_firmwareVersion
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    currentStorage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_camera_1api_canon_CanonCamera_currentStorage
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    currentFolder
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_camera_1api_canon_CanonCamera_currentFolder
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    lensName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_camera_1api_canon_CanonCamera_lensName
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    batteryLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_camera_1api_canon_CanonCamera_batteryLevel
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    batteryQuality
 * Signature: ()Lencodings/cameraprops/EdsBatteryQuality;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_batteryQuality
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    availableShots
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_camera_1api_canon_CanonCamera_availableShots
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    autoFocus
 * Signature: ()Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_autoFocus__
(JNIEnv*, jobject);

/*
 * Class:     CanonCamera
 * Method:    takePicture
 * Signature: ()Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_takePicture__
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    takePicture
 * Signature: (D)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_takePicture__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CanonCamera
 * Method:    cameraUILock
 * Signature: (Z)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_cameraUILock
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     CanonCamera
 * Method:    setLVSettingsStatus
 * Signature: (Lencodings/cameraprops/EdsLiveViewSettings;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setLVSettingsStatus
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getLVSettingsStatus
 * Signature: ()Lencodings/cameraprops/EdsLiveViewSettings;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getLVSettingsStatus
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setExposure
 * Signature: (Lencodings/cameraprops/EdsExposure;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setExposure
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getExposure
 * Signature: ()Lencodings/cameraprops/EdsExposure;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getExposure
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleExposure
 * Signature: ()[Lencodings/cameraprops/EdsExposure;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleExposure
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setISO
 * Signature: (Lencodings/cameraprops/EdsISO;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setISO
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getISO
 * Signature: ()Lencodings/cameraprops/EdsISO;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getISO
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleISO
 * Signature: ()[Lencodings/cameraprops/EdsISO;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleISO
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setFocusSettings
 * Signature: (Lencodings/cameraprops/EdsFocusSettings;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setFocusSettings
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getFocusSettings
 * Signature: ()Lencodings/cameraprops/EdsFocusSettings;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getFocusSettings
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleFocusSettings
 * Signature: ()[Lencodings/cameraprops/EdsFocusSettings;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleFocusSettings
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setAperture
 * Signature: (Lencodings/cameraprops/EdsAperture;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setAperture
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getAperture
 * Signature: ()Lencodings/cameraprops/EdsAperture;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getAperture
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleAperture
 * Signature: ()[Lencodings/cameraprops/EdsAperture;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleAperture
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setSaveTo
 * Signature: (Lencodings/cameraprops/EdsSaveTo;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setSaveTo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getSaveTo
 * Signature: ()Lencodings/cameraprops/EdsSaveTo;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getSaveTo
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setDriveMode
 * Signature: (Lencodings/cameraprops/EdsDriveMode;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setDriveMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getDriveMode
 * Signature: ()Lencodings/cameraprops/EdsDriveMode;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getDriveMode
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleDriveMode
 * Signature: ()[Lencodings/cameraprops/EdsDriveMode;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleDriveMode
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setMeteringMode
 * Signature: (Lencodings/cameraprops/EdsMeteringMode;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setMeteringMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getMeteringMode
 * Signature: ()Lencodings/cameraprops/EdsMeteringMode;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getMeteringMode
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleMeteringMode
 * Signature: ()[Lencodings/cameraprops/EdsMeteringMode;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleMeteringMode
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getBracketType
 * Signature: ()Lencodings/cameraprops/EdsBracket;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getBracketType
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setWhiteBalance
 * Signature: (Lencodings/cameraprops/EdsWhiteBalance;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setWhiteBalance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getWhiteBalance
 * Signature: ()Lencodings/cameraprops/EdsWhiteBalance;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getWhiteBalance
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleWhiteBalance
 * Signature: ()[Lencodings/cameraprops/EdsWhiteBalance;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleWhiteBalance
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setColorSpace
 * Signature: (Lencodings/cameraprops/EdsColorSpace;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setColorSpace
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getColorSpace
 * Signature: ()Lencodings/cameraprops/EdsColorSpace;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getColorSpace
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleColorSpace
 * Signature: ()[Lencodings/cameraprops/EdsColorSpace;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleColorSpace
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setPictureStyle
 * Signature: (Lencodings/cameraprops/EdsPictureStyle;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setPictureStyle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPictureStyle
 * Signature: ()Lencodings/cameraprops/EdsPictureStyle;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getPictureStyle
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossiblePictureStyle
 * Signature: ()[Lencodings/cameraprops/EdsPictureStyle;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossiblePictureStyle
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getLensStatus
 * Signature: ()Lencodings/cameraprops/EdsLensStatus;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getLensStatus
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setAEModeSelect
 * Signature: (Lencodings/cameraprops/EdsAEModeSelect;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setAEModeSelect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getAEModeSelect
 * Signature: ()Lencodings/cameraprops/EdsAEModeSelect;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getAEModeSelect
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleAEModeSelect
 * Signature: ()[Lencodings/cameraprops/EdsAEModeSelect;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleAEModeSelect
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setExposureComp
 * Signature: (Lencodings/cameraprops/EdsExposureComp;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setExposureComp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getExposureComp
 * Signature: ()Lencodings/cameraprops/EdsExposureComp;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getExposureComp
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getPossibleExposureComp
 * Signature: ()[Lencodings/cameraprops/EdsExposureComp;
 */
JNIEXPORT jobjectArray JNICALL Java_camera_1api_canon_CanonCamera_getPossibleExposureComp
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    getAEMode
 * Signature: ()Lencodings/cameraprops/EdsAEMode;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getAEMode
  (JNIEnv *, jobject);

/*
 * Class:     CanonCamera
 * Method:    setSummerTimeSetting
 * Signature: (Lencodings/cameraprops/EdsSummerTimeSetting;)Lencodings/sdk/EdsError;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_setSummerTimeSetting
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CanonCamera
 * Method:    getSummerTimeSetting
 * Signature: ()Lencodings/cameraprops/EdsSummerTimeSetting;
 */
JNIEXPORT jobject JNICALL Java_camera_1api_canon_CanonCamera_getSummerTimeSetting
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
